/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Notification`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/QrcodeScanner`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownInputParams; } | { pathname: `/screens/earnedBadges`; params?: Router.UnknownInputParams; } | { pathname: `/screens/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/notificationDetails`; params?: Router.UnknownInputParams; } | { pathname: `/screens/pointRanking`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BottomNavigation`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/MapScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Notification`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/QrcodeScanner`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/earnedBadges`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/editProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/notificationDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/pointRanking`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/BottomNavigation${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/Login${`?${string}` | `#${string}` | ''}` | `/screens/MapScreen${`?${string}` | `#${string}` | ''}` | `/screens/Notification${`?${string}` | `#${string}` | ''}` | `/screens/Profile${`?${string}` | `#${string}` | ''}` | `/screens/QrcodeScanner${`?${string}` | `#${string}` | ''}` | `/screens/Register${`?${string}` | `#${string}` | ''}` | `/screens/earnedBadges${`?${string}` | `#${string}` | ''}` | `/screens/editProfile${`?${string}` | `#${string}` | ''}` | `/screens/notificationDetails${`?${string}` | `#${string}` | ''}` | `/screens/pointRanking${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/BottomNavigation`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Login`; params?: Router.UnknownInputParams; } | { pathname: `/screens/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Notification`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/QrcodeScanner`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Register`; params?: Router.UnknownInputParams; } | { pathname: `/screens/earnedBadges`; params?: Router.UnknownInputParams; } | { pathname: `/screens/editProfile`; params?: Router.UnknownInputParams; } | { pathname: `/screens/notificationDetails`; params?: Router.UnknownInputParams; } | { pathname: `/screens/pointRanking`; params?: Router.UnknownInputParams; };
    }
  }
}
